# Random Forest Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

C:\Users\ajitg\miniconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\ajitg\miniconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\ajitg\miniconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


## Importing the dataset

In [2]:
data = pd.read_csv('Data.csv')


In [42]:
data.shape

(11055, 10)

In [43]:
data.drop_duplicates(keep=False, inplace=True)


In [44]:
data.shape

(11055, 10)

In [4]:
data.head()

index  having_IP_Address  URL_Length  SSLfinal_State  Request_URL  \
0      1                 -1           1              -1            1   
1      2                  1           1               1            1   
2      3                  1           0              -1            1   
3      4                  1           0              -1           -1   
4      5                  1           0               1            1   

   URL_of_Anchor  SFH  popUpWidnow  age_of_domain  Result  
0             -1   -1            1             -1      -1  
1              0   -1            1             -1      -1  
2              0   -1            1              1      -1  
3              0   -1            1             -1      -1  
4              0   -1           -1             -1       1

In [27]:
dis = data['Result'].value_counts()
dis

 1    6157
-1    4898
Name: Result, dtype: int64

In [5]:
X = data.iloc[:,1:-1].values
Y = data.iloc[:,-1].values

In [6]:
X

array([[-1,  1, -1, ..., -1,  1, -1],
       [ 1,  1,  1, ..., -1,  1, -1],
       [ 1,  0, -1, ..., -1,  1,  1],
       ...,
       [ 1, -1, -1, ..., -1,  1,  1],
       [-1, -1, -1, ..., -1, -1,  1],
       [-1, -1, -1, ..., -1,  1, -1]], dtype=int64)

In [7]:
Y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [8]:
Y.shape

(11055,)

## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [10]:
print(X_train)

[[ 1 -1  1 ... -1  1  1]
 [ 1 -1  1 ... -1  1  1]
 [ 1 -1 -1 ... -1  1  1]
 ...
 [-1  1  1 ... -1  1  1]
 [-1 -1  0 ... -1  1  1]
 [ 1 -1  1 ... -1 -1  1]]


In [11]:
print(y_train)

[ 1  1  1 ...  1 -1 -1]


In [12]:
print(X_test)

[[ 1 -1  1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1  1 -1]
 [ 1 -1  1 ... -1  1  1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]
 [ 1 -1 -1 ... -1  1  1]]


In [13]:
print(y_test)

[-1 -1 -1 ... -1  1 -1]


## Training the Random Forest Classification model on the Training set

In [14]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting a new result

In [15]:
# print(classifier.predict(sc.transform([[30,87000]])))

## Predicting the Test set results

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1 -1]
 [-1 -1]
 [ 1 -1]
 ...
 [-1 -1]
 [-1  1]
 [-1 -1]]


## Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1102  147]
 [  76 1439]]


0.9193198263386396

In [29]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("Mean squared error: ", mse)

Mean squared error:  0.3227206946454414


In [30]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

print("R-squared:", r2)

R-squared: 0.6742624462606388


In [86]:
import pickle
filename = 'mainPickle.pkl'
with open(filename, 'wb') as file:
  pickle.dump(grid_search, file)

In [87]:
import joblib
RF = joblib.load('mainPickle.pkl')

testy = RF.predict([[-1,1,1,1,1,1,1,-1]])
testy

array([1], dtype=int64)

In [82]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = [
{'n_estimators': [1,2,3,10,20,30,40,100,300],'max_depth': [4,6,8,10,12,14],'max_features': [10],'min_samples_split': [6,7,8]},
]
forest_reg = RandomForestClassifier()
grid_search = GridSearchCV(forest_reg, param_grid, cv=5,
scoring='neg_mean_squared_error',
return_train_score=True)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid=[{'max_depth': [4, 6, 8, 10, 12, 14],
                          'max_features': [10], 'min_samples_split': [6, 7, 8],
                          'n_estimators': [1, 2, 3, 10, 20, 30, 40, 100, 300]}],
             return_train_score=True, scoring='neg_mean_squared_error')

In [83]:
grid_search.best_params_

{'max_depth': 12,
 'max_features': 10,
 'min_samples_split': 7,
 'n_estimators': 3}

In [84]:
from sklearn.metrics import r2_score
y_pred = grid_search.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("R-squared:", r2)

R-squared: 0.6830266853747022


In [85]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("Mean squared error: ", mse)

Mean squared error:  0.3140376266280753


In [68]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(X_train, y_train)

LogisticRegression()

In [70]:
predictions = LR.predict(X_test)


In [71]:

r2 = r2_score(y_test, predictions)

print("R-squared:", r2)

R-squared: 0.6275198376522999
